import { Poppins } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Cardapia",
  description: "Generated by create next app",
  icons: {
    icon: "/imagens/comida.png",
  },
};


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Defina os pesos que você vai usar
  variable: '--font-poppins',    // Cria uma variável CSS
});

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.variable} font-sans`}>
        {children}
        <link></link>
      </body>
    </html>
  );
}
